# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Salesforce OAuth Demo' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Salesforce OAuth Demo
  pod 'SalesforceSDKCore'

  target 'Salesforce OAuth DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
