# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

target 'ChatbotTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatbotTestApp
  
  pod 'ServiceSDK/Chat'
  
  target 'ChatbotTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
